name: yuuki_mart
description: Flutter app designed to help people find organic supermarkets, restaurants, farmer's markets, and more.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  redux: ^5.0.0
  flutter_redux: ^0.10.0
  font_awesome_flutter:
  intl: ^0.17.0
  maps_launcher: ^2.0.1
  url_launcher: ^6.1.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: Fonts/Comfortaa-Regular.ttf
  generate: true
  uses-material-design: true
  assets:
    - Images/
    - Images/MartType/

